---
title: "Plot validation"
author: "Anna Boser"
date: '2022-03-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(data.table)
library(here)
library(dplyr)
library(sf)
library(tmap)
```

```{r}
data <- read.csv(here("data", "for_analysis", "regressor_validation_cv", "sklearn_RF_full_cv_outputs_1x1.csv"))
```

```{r}
data$lon <- floor(data$cv_fold/1000)
data$lat <- data$cv_fold - data$lon*1000
```

```{r}
CV_grid <- raster(here("data", "intermediate", "CA_grid_cv.tif"))
CA <- st_read(here("data", "raw", "shapefiles", "california", "california.shp")) %>% st_transform(st_crs(CV_grid))
CV <- st_read(here("data", "raw", "shapefiles", "cimis_CV", "cimis_CV.shp")) %>% st_transform(st_crs(CV_grid))

# make a raster of 1x1 degree cells
raster = raster(#nrows=10, 
                #ncols=11, 
                xmn=min(data$lon), 
                xmx=max(data$lon) + 1, # because of the flooring operation
                ymn=min(data$lat), 
                ymx=max(data$lat) + 1, 
                crs = st_crs(CV), 
                resolution = 1, 
                vals=1:35)

# turn it into a shapefile since that'll be easier
sf = rasterToPolygons(raster)
sf <- st_as_sf(sf)
st_crs(sf) <- st_crs(CV)

```

```{r}
# crs(sf) <- st_crs(CV)
tm_shape(sf) + tm_polygons(col="layer") + tm_shape(CV) + tm_borders()
```

```{r}
# remove the ones that do not overlap with the central valley
sf1 <- sf[CV,]
tm_shape(sf1) + tm_polygons(col="layer") + tm_shape(CV) + tm_borders()
```


```{r}
head(data)
```


```{r}
data %>% 
  ggplot() + 
  geom_point(aes(x = ET, y= ET_pred, col = lat), alpha = .2, size = .1)
```

```{r}
data %>% 
  ggplot() + 
  geom_point(aes(x = ET, y= ET_pred, col = factor(monthgroup)), alpha = .2, size = .1)
```


```{r}
data %>% 
  group_by(lon, lat) %>%
  summarise(rmse = mean((ET_pred-ET)^2), 
            mae = mean(abs(ET_pred-ET))) %>%
  ggplot() +
  geom_point(aes(x = lon, y = lat, col = mae))
  
  
```

