---
title: "Analysis"
author: "Anna Boser"
date: '2022-05-02'
output: html_document
---

```{r}
library(here)
library(tidyr)
library(dplyr)
library(ggplot2)
library(rgdal)
library(maptools)
library(data.table)
library(sf)
```


# First glance at ET in agriculture 

## Read in the data
```{r}
data <- fread(file = here("data/for_analysis/ag_counterfactual/ag_counterfactual_default<5.csv"))
```


```{r}
# Average over monthgroups

data <- pivot_wider(data, names_from = c(monthgroup), values_from = c(ET, ET_pred, ag_ET, PET))

data$ET <- rowMeans(select(data, ET_2, ET_3, ET_4))
data$ET_pred <- rowMeans(select(data, ET_pred_2, ET_pred_3, ET_pred_4))
data$ag_ET <- rowMeans(select(data, ag_ET_2, ag_ET_3, ag_ET_4))
data$PET <- rowMeans(select(data, PET_2, PET_3, PET_4))

data <- data %>% select(-ET_2, -ET_3, -ET_4, -ET_pred_2, -ET_pred_3, -ET_pred_4, -ag_ET_2, -ag_ET_3, -ag_ET_4, -PET_2, -PET_3, -PET_4)
```

## Make histograms

```{r}
hist_data <- pivot_longer(data, cols=c(ET, ET_pred, ag_ET), names_to="type", values_to="ET")
hist_data$type <- factor(hist_data$type, levels=c("ET", "ET_pred", "ag_ET"))
```

```{r}
# also include the original natural lands in the densities
data_natural <- fread(here("data", "for_analysis", "counterfactual_cv_gs_mm<5.csv"))

# Average over monthgroups

data_natural <- pivot_wider(data_natural, names_from = c(monthgroup), values_from = c(ET, PET))

data_natural$ET <- rowMeans(select(data_natural, ET_2, ET_3, ET_4))
data_natural$PET <- rowMeans(select(data_natural, PET_2, PET_3, PET_4))

data_natural <- data_natural %>% select(-ET_2, -ET_3, -ET_4, -PET_2, -PET_3, -PET_4)

data_natural$type <- "natural"

hist_data <- rbind(hist_data, data_natural)
```

```{r}
# check the average difference between natural ET and simulated natural ET 
mean(filter(hist_data, type == "natural")$ET, na.rm = TRUE)
mean(filter(hist_data, type == "ET_pred")$ET, na.rm = TRUE)
mean(filter(hist_data, type == "ag_ET")$ET, na.rm = TRUE)
```


```{r}
ggplot(hist_data) + 
  geom_density(aes(x=ET, fill = type), lwd = 0, alpha = .4) + 
  scale_fill_manual(name="", labels=c("Observed ET on agricultural lands", "Simulted natural ET", "Agricultural water consumption", "Observed ET on natural lands"), values=c("navyblue", "darkgoldenrod4", "seagreen", "grey")) +
  theme_classic() +  
  theme(legend.position = c(0.75, 0.8),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  xlab("ET (mm/day)")
```


## Make maps of ET, ET_pred, and ag_ET

To do this I probably need to first turn it back into a raster? I'd like to plot the outline of the CV and then all the ag spots inside. 

```{r}
CV <- readOGR(here("data", "raw", "shapefiles", "cimis_CV", "cimis_CV.shp"))
CV <- spTransform(CV, CRS("+proj=longlat +datum=WGS84"))
CV <- fortify(CV)
```

```{r}
data <- pivot_longer(data, cols=c(ET, ET_pred, ag_ET), names_to="type", values_to="ET")
data$type <- factor(data$type, levels=c("ET", "ET_pred", "ag_ET"))
```

```{r}
# read in the county shapefiles to make a pretty map
counties <- st_read(here("data", "raw", "shapefiles", "study_area_counties", "study_area_counties.shp"))
```

```{r}
# data1 <- data[sample(nrow(data), size = 100000, replace = FALSE),] # subset for fast testing

new.labs <- c("Observed ET", "Simulated natural ET", "Agricultural water consumption")
names(new.labs) <- c("ET", "ET_pred", "ag_ET")

ggplot() + 
  geom_sf(data = counties, color=alpha("white",1), size = .2) + 
  geom_raster(data = data, aes(x=x, y=y, fill=ET)) +
  facet_grid(cols=vars(type), labeller = labeller(type = new.labs)) +
  scale_fill_gradientn(name="ET (mm/day)", colours = c("darkgoldenrod4", "darkgoldenrod2", "khaki1", "lightgreen", "turquoise3", "deepskyblue3", "mediumblue", "navyblue", "midnightblue", "black"), limits = c(-2.5, 8)) +
  geom_polygon(data = CV, aes(long, lat, group=group), colour = alpha("black", 1), fill = NA, size = .3) +
  xlim(c(-122.92, -118.6)) + 
  ylim(c(34.94, 40.754)) + 
  theme_classic() +
  theme(legend.position = c(0.92, 0.79),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

