---
title: "1.5_combine_ETandPET"
author: "Anna Boser"
date: "1/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# get the ET file names
files <- list.files(path = here("data", "raw", "ECOSTRESS"), full.names = TRUE)

# empty consistent grid
CA_grid <- raster(here("data", "intermediate", "CA_grid.tif"))

# ag and natural land rasters
ag <- raster(here("data", "intermediate", "agriculture", "ag_indicator.tif"))
natural <- raster(here("data", "intermediate", "counterf", "counterf_indicator.tif"))
pixels_of_interest <- ag|natural

# full, time invariant grid
full <- fread(here("data", "for_analysis", "full_grid_time_invariant.csv"))

# remove entries that are neither ag nor natural
full <- full[agriculture == 1|counterfactual == 1]
fwrite(full, here("data", "for_analysis", "ag_count_time_invariant.csv"))
```

1. Make dataset that isn't broken up by month -- the yearly average dataset. Deal with the monthly stuff later for paper #2. 

```{r}
PET <- raster(here("data", "intermediate", "PET", "PET_yeargrouped_avg.tif"))

PET_ag <- mask(PET, ag)
PET_df_ag <- as.data.frame(PET_ag, xy = TRUE, na.rm = TRUE)

full_ag <- full <- full[agriculture == 1]

full_ag <- merge(full_ag, PET_df_ag, by = c(x,y), all.x = TRUE, all.y = FALSE)
```

```{r}
PET_nat <- mask(PET, natural)
PET_df_nat <- as.data.frame(PET_nat)

full_nat <- full <- full[counterfactual == 1]

full_nat <- merge(full_nat, PET_df_nat, by = c(x,y), all.x = TRUE, all.y = FALSE)
```





```{r}
full <- fread(here("data", "for_analysis", "ag_count_time_invariant.csv"))

i <- 1

PET <- raster(here("data", "intermediate", "PET", paste0("PET_grouped_", i ,".tif")))
PET <- mask(PET, pixels_of_interest)
df <- as.data.frame(PET, xy = TRUE, na.rm = TRUE)
```

```{r}
merge(full, df, by = c(x,y), all.x = TRUE, all.y = FALSE)
```

