---
title: "county level stats"
author: "Anna Boser"
date: '2022-05-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(stringr)
library(sf)
library(tmap)
library(data.table)
library(tidyr)
library(dplyr)
library(ggplot2)
```

```{r}
####################################
# county shapefiles
####################################

counties <- st_read(here("data", "raw", "shapefiles", "study_area_counties", "study_area_counties.shp"))
```

```{r}
####################################
# DWR crop data
####################################

DWR <- read_sf(here("data", "raw", "DWR_crop", "i15_Crop_Mapping_2018.shp")) 
DWR <- st_zm(DWR) # DWR in 3 dims with 0 for z value
DWR <- filter(DWR, CLASS2 != "U") # remove Urban

# for each county, get the area of farmland in m^2
flatten <- function(s){
  d <- filter(DWR, CLASS2 == s) %>% st_make_valid()
  d <- st_union(d) %>% st_as_sf() %>% st_make_valid()
  d$CLASS2 = s
  return(d)
}

ss <- unique(DWR$CLASS2)

DWR_flat <- lapply(ss, flatten)
DWR_flat <- do.call(rbind, DWR_flat)

st_write(DWR_flat, here("data", "intermediate", "agriculture", "ag_classes.shp")) # save this

ag_by_county <- as_tibble(st_intersection(DWR_flat, counties))
ag_by_county$area <- st_area(ag_by_county$x)
ag_by_county$x <- NULL

ag_area_by_county <- ag_by_county %>% 
  group_by(NAME) %>%
  summarise(total_ag_m2 = sum(area))

counties <- base::merge(counties, ag_area_by_county, by = "NAME", all.x = TRUE)
counties$total_ag_m2 <- ifelse(is.na(counties$total_ag_m2), ag_by_county$area[1]*0, counties$total_ag_m2)

# for each county, get the area of each crop type
crop_area_by_county <- ag_by_county %>%
  select("NAME", "area", "CLASS2") %>% 
  pivot_wider(names_from = "CLASS2", values_from = "area", names_prefix = "m2_", values_fill = ag_by_county$area[1]*0)

counties <- base::merge(counties, crop_area_by_county, by = "NAME", all.x = TRUE)

# for each county, get the percent of each crop type
ag_by_county <- merge(ag_by_county, ag_area_by_county, by = "NAME")
ag_by_county$frac = ag_by_county$area/ag_by_county$total_ag_m2

crop_frac_by_county <- ag_by_county %>%
  select("NAME", "frac", "CLASS2") %>% 
  pivot_wider(names_from = "CLASS2", values_from = "frac", names_prefix = "frac_", values_fill = ag_by_county$area[1]*0/ag_by_county$area[1]*0)

counties <- base::merge(counties, crop_frac_by_county, by = "NAME", all.x = TRUE)

# for each county, get the area of farmland within the CV study area

CV <- st_read(here("data", "raw", "shapefiles", "cimis_CV", "cimis_CV.shp")) %>% st_transform(st_crs(DWR))# central valley shapefile
DWR_CV <- st_intersection(DWR_flat, CV)

ag_by_county_CV <- as_tibble(st_intersection(DWR_CV, counties))
ag_by_county_CV$area <- st_area(ag_by_county_CV$x)
ag_by_county_CV$x <- NULL

ag_area_by_county_CV <- ag_by_county_CV %>% 
  group_by(NAME) %>%
  summarise(total_ag_m2_CV = sum(area))

counties <- base::merge(counties, ag_area_by_county_CV, by = "NAME", all.x = TRUE)
counties$total_ag_m2_CV <- ifelse(is.na(counties$total_ag_m2_CV), ag_by_county_CV$area[1]*0, counties$total_ag_m2_CV)

# get the fraction of farmland that's in the study area
counties$ag_CV_frac <- counties$total_ag_m2_CV/counties$total_ag_m2

# get crop cover within the CV
crop_area_by_county_CV <- ag_by_county_CV %>%
  select("NAME", "area", "CLASS2") %>% 
  pivot_wider(names_from = "CLASS2", values_from = "area", names_prefix = "m2_CV", values_fill = ag_by_county$area[1]*0)

counties <- base::merge(counties, crop_area_by_county_CV, by = "NAME", all.x = TRUE)

# save this file
dir.create(here("data", "intermediate", "counties"))
st_write(counties, here("data", "intermediate", "counties", "counties_ag_stats.shp")) # save this
```












