---
title: "crops comparison"
author: "Anna Boser"
date: '2022-05-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(stringr)
library(sf)
library(tmap)
library(data.table)
library(tidyr)
library(dplyr)
library(ggplot2)
library(latex2exp)
```

```{r}
# read ET data
data <- fread(file = here("data/for_analysis/ag_counterfactual/ag_counterfactual_default0.1.csv"))
```

```{r}
# read county information and merge with ET data
crops <- fread(file=file.path(here("data", "intermediate", "crops", "crops.csv")))
crops$x <- round(crops$x, 7)
crops$y <- round(crops$y, 7)
data$x <- round(data$x, 7)
data$y <- round(data$y, 7)
data <- merge(data, crops, by = c("x", "y"))
rm(crops)
```

Check how water use varies by crop
```{r}
bardata = data %>% 
  pivot_longer(cols=c(ET, ET_pred, ag_ET), names_to="type", values_to="ET") %>%
  group_by(cropnames, type) %>%
  summarize(min=mean(ET) - 1.96*sd(ET)/(n()-1), 
            max=mean(ET) + 1.96*sd(ET)/(n()-1),
            ET = mean(ET)
            ) 

bardata$type <- factor(bardata$type, levels=c("ET", "ET_pred", "ag_ET"))

ggplot(bardata, aes(x = reorder(cropnames, ET))) + 
  geom_col(aes(y = ET, fill = cropnames)) +
  geom_linerange(aes(ymin = min, ymax=max)) +
  facet_grid(cols = vars(type)) +
  scale_fill_manual(values = c("Pasture" = "green3", 
                                    "Grain and hay crops" = "gold", 
                                    "Vineyards" = "slateblue",
                                    "Truck, nursery, and berry crops" = "palevioletred", 
                                    "Deciduous fruits and nuts" = "forestgreen", 
                                    "Field crops" = "wheat", 
                                    "Young Perennial" = "lightgreen", 
                                    "Idle" = "grey", 
                               "Unclassified fallow" = "tan4", 
                               "Citrus and subtropical" = "yellow", 
                               "Rice" = "beige")) + 
  theme(axis.text.x=element_blank(), 
        axis.title.x=element_blank(), 
        axis.ticks.x=element_blank(), 
        axis.title.y=element_blank())
```

Get rid of ET, only plot ag_ET and ET_pred
```{r}
bardata2 <- filter(bardata, type != "ET")


ggplot(bardata2, aes(x = reorder(cropnames, ET))) + 
  geom_col(aes(y = ET, fill = type), alpha = .9) +
  scale_fill_manual(values=c("darkgoldenrod4", "seagreen"), labels = c("Naturally occuring ET", "Agricultural water consumption")) + 
  ylab("Observed ET (mm/day)") + 
  theme_classic() + 
  labs(fill='') + 
  theme(axis.text.x = element_text(angle = 30, hjust=1), 
        axis.title.x=element_blank(), 
        axis.ticks.x=element_blank(), 
        legend.position = c(0.2, 0.9))
```








California’s irrigated pasturelands—including valley, foothill, and mountain meadow pastures— account for nearly 500,000 acres across the state, and ranks third among agricultural water users. https://rangelands.ucdavis.edu/ipep/

```{r}
ggplot(data) + 
  geom_boxplot(aes(x = reorder(cropnames, ET), y = ag_ET, color = cropnames)) + 
    scale_color_manual(values = c("Pasture" = "green3", 
                                    "Grain and hay crops" = "gold", 
                                    "Vineyards" = "slateblue",
                                    "Truck, nursery, and berry crops" = "palevioletred", 
                                    "Deciduous fruits and nuts" = "forestgreen", 
                                    "Field crops" = "wheat", 
                                    "Young Perennial" = "lightgreen", 
                                    "Idle" = "grey", 
                               "Unclassified fallow" = "tan4", 
                               "Citrus and subtropical" = "yellow", 
                               "Rice" = "beige")) + 
  theme_classic() +
  theme(axis.text.x=element_blank(), 
        axis.title.x=element_blank(), 
        axis.ticks.x=element_blank()) 
```

```{r}

```

